[project]
name = "environments-mpm"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10",
    "numpy>=2.1",
    "pandas>=2.3.3",
    "scikit-image>=0.25.2",
    "scipy>=1.16.2",
    "sympy>=1.14.0",
]
